### ISSUE TITLE
Solaris compile errors

### ISSUE THREAD

**Issue by benkasminbullock** [benkasminbullock/JSON-Parse#31]
http://matrix.cpantesters.org/?dist=JSON-Parse+0.39

Have written to BINGOS as follows on 28/12/2015 (10 days ago):

---

Dear Chris Williams,

Thank you for your efforts in CPAN testing.

I have recently received many test failures like this one:

http://www.cpantesters.org/cpan/report/db90a722-abaa-11e5-9a42-4da8aef69d38

I cannot fathom this error

symbol ucs2_to_utf8: referenced symbol not found

or the error

perl: fatal: relocation error:

It is a single C file and the symbol should normally be in that.

What can I do about this?

Thank you.

Ben Bullock

---

Awaiting reply.

**Comment by bingos** [comment]
I have confirmed it on a different Solaris machine (the original Solaris machine has some issues with its zpool, but that is unrelated to this issue).

It also appears that ActiveState have the same problems in their PPM builder:
http://ppm4.activestate.com/sun4-solaris/5.12/1200/B/BK/BKB/JSON-Create-0.01.d/log-20151019T183520.txt

I have no idea why the error is generated though.

**Comment by benkasminbullock** [comment]
Thanks very much for the insight particularly about the ActiveState compilation which confirms that it is something I need to alter rather than being a testing failure on your part.

The C file is included here:

https://github.com/benkasminbullock/JSON-Parse/blob/74ae84b9de2026324e3f91e84721ab3468f275fc/Json3.xs#L23

It is very odd that this symbol cannot be located. A possible workaround is to generate the XS file using template toolkit or other system rather than relying on #include system.

**Comment by benkasminbullock** [comment]
Cannot really support OSes to which I have no access, so for version 0.54 I have removed Solaris support.

Closing this issue.
