### ISSUE TITLE
Please add documentation on how to build this distro from the repo

### ISSUE THREAD

**Issue by shlomif** [benkasminbullock/JSON-Parse#32]
Hi!

I'm completely lost with how to build this dist from the repo. Nothing that I tried worked. Please add some documentation for that in README/INSTALL/etc.:

here is what I tried:

```
bash-4.3$ perl Makefile.PL 
Could not open 'lib/JSON/Parse.pod': No such file or directory at /home/shlomif/perl5/perlbrew/perls/perl-5.22.2-RC1/lib/5.22.2/ExtUtils/MM_Unix.pm line 2695.
bash-4.3$ perl b
benchmarks/ build.pl    
bash-4.3$ perl build.pl 
Undefined subroutine &main::perl_build called at build.pl line 5.
bash-4.3$ perl mak
make-errors.pl  make-pod.pl     
bash-4.3$ perl make-pod.pl 
Can't locate Table/Readable.pm in @INC (you may need to install the Table::Readable module) (@INC contains: blib/lib blib/arch /home/shlomif/perl5/perlbrew/perls/perl-5.22.2-RC1/lib/site_perl/5.22.2/x86_64-linux /home/shlomif/perl5/perlbrew/perls/perl-5.22.2-RC1/lib/site_perl/5.22.2 /home/shlomif/perl5/perlbrew/perls/perl-5.22.2-RC1/lib/5.22.2/x86_64-linux /home/shlomif/perl5/perlbrew/perls/perl-5.22.2-RC1/lib/5.22.2 .) at make-pod.pl line 9.
BEGIN failed--compilation aborted at make-pod.pl line 9.
bash-4.3$ cpan -i Table::Readable
Loading internal null logger. Install Log::Log4perl for logging messages
CPAN: Storable loaded ok (v2.53_01)
Reading '/home/shlomif/.cpan/Metadata'
  Database was generated on Fri, 13 May 2016 09:53:45 GMT
Warning: Cannot install Table::Readable, don't know what it is.
Try the command

    i /Table::Readable/

to find objects with matching identifiers.
CPAN: Time::HiRes loaded ok (v1.9726)
bash-4.3$ 

```

This is part of the CPAN pull-request challenge assignment.

**Comment by benkasminbullock** [comment]
Hi,

This uses a private build module. I will put it on github later on.

Its name is Perl::Build but it predates the Perl::Build by TOKUHIROM on
CPAN. Maybe I could change that name.

You also need Table::Readable.

Please could you outline what work you will do on the module.

Thank you.

Ben Bullock

**Comment by shlomif** [comment]
I was planning on investigating the clang warnings and maybe fixing some of them.

**Comment by benkasminbullock** [comment]
I think I will make a branch with the built files included in it and you
can work from that.

I'll send another message later on.

**Comment by benkasminbullock** [comment]
Please use this repository:

https://github.com/benkasminbullock/JSON-Parse/tree/fish

You can just make with "perl Makefile.PL" I think.

Let me know if anything else needs to be done.

Thanks.

**Comment by benkasminbullock** [comment]
Hi again,

Was that OK or not?

Let me know.

Ben

**Comment by shlomif** [comment]
@benkasminbullock : yes, I can run "perl Makefile.PL" ; "make" and "make test" fine. Sorry I've been unresponsive, but I got distracted . I'd like to tend to it though.

**Comment by benkasminbullock** [comment]
Thank you very much for these additions which have been added to version
0.40 released to CPAN. I also worked on the documentation a bit for this
release.

Let me know if you have any more suggestions.

Ben Bullock

**Comment by benkasminbullock** [comment]
I'm planning to rename my build thing from Perl::Build to BKB::Build or something and put it back on github. It was originally called Perl::Build and was on github, then someone else used the name (the Perl::Build on CPAN came after mine), so I'll give it a name which is more unique and set it up.

Closing the issue here, anyway.
