### ISSUE TITLE
Should at least recommend Path::Tiny

### ISSUE THREAD

**Issue by kentfredric** [benkasminbullock/JSON-Parse#36]
The installed scripted "validjson" uses `Path::Tiny`, which implies the utility should state a dependency.

I'd probably want it as a `runtime.requires`, but a `runtime.recommends` would probably suffice if you're trying to keep the deptree lean.

**Comment by benkasminbullock** [comment]
Thank you for reporting this bug.

That is documented here:

https://metacpan.org/pod/distribution/JSON-Parse/lib/JSON/Parse.pod#SCRIPT

I'll remove the dependency in a future release since I do not use
Path::Tiny any more.

Thanks again

Ben Bullock

**Comment by kentfredric** [comment]
If you simply nuke the "use lib" lines , relocate the content to "examples/" and remove the script from the install list in Makefile.PL, it would serve as an "Ok" example of usage. 

That would also remove the need to declare dependencies.

**Comment by benkasminbullock** [comment]
I've extensively updated the script to remove Path::Tiny and also tidy up the rather unpleasant messages.

Is there actually a reason the script needs to be removed? I didn't get that message from your original bug report. Supposing someone is using the script, they might be upset if I removed it, so I'd rather not unless there is an active problem that the script is causing.

**Comment by kentfredric** [comment]
Oh, no, I must have gotten confused about what you've said :) I somehow interpreted *you* said you were going to remove the executable script, and I was trying to discourage a total removal :)

Keeping it is entirely fine with me :D

**Comment by kentfredric** [comment]
Closing now as the primary reason for this ticket is now satisfied.

**Comment by benkasminbullock** [comment]
Thank you again for reporting this. Please let me know if you find anything else of concern with the module.
