### ISSUE TITLE
Error building on Strawberry Perl

### ISSUE THREAD

**Issue by gquipster** [benkasminbullock/JSON-Parse#38]
Hi,

Had an issue installing 0.52 on Strawberry Perl:

"C:\strawberry\perl\bin\perl.exe" -MExtUtils::Command -e mv -- Json3.xsc Json3.c
gcc -c          -s -O2 -DWIN32 -DWIN64 -DCONSERVATIVE -DPERL_TEXTMODE_SCRIPTS -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -DUSE_PERLIO -fno-strict-aliasing -mms-bitfields -s -O2         -DVERSION=\"0.52\"    -DXS_VERSION=\"0.52\"  "-IC:\strawberry\perl\lib\CORE"   Json3.c
In file included from Json3.xs:23:0:
unicode.c:98:1: error: unknown type name 'uint8_t'
In file included from Json3.xs:23:0:
unicode.c:103:1: error: unknown type name 'int32_t'
In file included from Json3.xs:23:0:
unicode.c:124:1: error: unknown type name 'int32_t'
In file included from Json3.xs:23:0:
unicode.c:159:1: error: unknown type name 'int32_t'
In file included from Json3.xs:23:0:
unicode.c:248:1: error: unknown type name 'int32_t'
unicode.c:248:23: error: unknown type name 'int32_t'
In file included from Json3.xs:23:0:
unicode.c:293:1: error: unknown type name 'int32_t'
unicode.c:293:50: error: unknown type name 'int32_t'
unicode.c:293:67: error: unknown type name 'int32_t'
In file included from Json3.xs:23:0:
unicode.c:312:1: error: unknown type name 'int32_t'
unicode.c:312:32: error: unknown type name 'int32_t'
unicode.c:312:44: error: unknown type name 'int32_t'
In file included from Json3.xs:23:0:
unicode.c:334:1: error: unknown type name 'int32_t'
unicode.c:334:28: error: unknown type name 'int32_t'
unicode.c:334:40: error: unknown type name 'int32_t'
In file included from Json3.xs:23:0:
unicode.c:347:1: error: unknown type name 'int32_t'
unicode.c:347:60: error: unknown type name 'int32_t'
In file included from Json3.xs:23:0:
unicode.c:366:1: error: unknown type name 'int32_t'
In file included from Json3.xs:23:0:
unicode.c:387:1: error: unknown type name 'int32_t'
In file included from Json3.xs:23:0:
unicode.c:474:1: error: unknown type name 'int32_t'
unicode.c:474:49: error: unknown type name 'int32_t'
In file included from Json3.xs:23:0:
unicode.c:611:1: error: unknown type name 'int32_t'
In file included from Json3.xs:23:0:
unicode.c:632:28: error: unknown type name 'int32_t'
In file included from Json3.xs:24:0:
unicode.c:123:15: error: conflicting types for 'utf8_sequence_len'
In file included from Json3.xs:23:0:
unicode.c:98:22: note: previous declaration of 'utf8_sequence_len' was here
dmake:  Error code 129, while making 'Json3.o'

I fixed this by changing the start of Json3.c from:

#line 1 "Json3.xs"
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

To:

#line 1 "Json3.xs"
#include "EXTERN.h"
#include "perl.h"
#include "stdint.h"
#include "XSUB.h"

After which:

C:\strawberry\cpan\build\JSON-Parse-0.52-0>dmake
"C:\strawberry\perl\bin\perl.exe" -MExtUtils::Command::MM -e cp_nonempty -- Parse.bs blib\arch\auto\JSON\Parse\Parse.bs 644
gcc -c          -s -O2 -DWIN32 -DWIN64 -DCONSERVATIVE -DPERL_TEXTMODE_SCRIPTS -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -DUSE_PERLIO -fno-strict-aliasing -mms-bitfields -s -O2         -DVERSION=\"0.52\"    -DXS_VERSION=\"0.52\"  "-IC:\strawberry\perl\lib\CORE"   Json3.c
"C:\strawberry\perl\bin\perl.exe" -MExtUtils::Mksymlists \
     -e "Mksymlists('NAME'=>\"JSON::Parse\", 'DLBASE' => 'Parse', 'DL_FUNCS' => {  }, 'FUNCLIST' => [], 'IMPORTS' => {  }, 'DL_VARS' => []);"
g++ Parse.def -o blib\arch\auto\JSON\Parse\Parse.dll -mdll -s -L"C:\strawberry\perl\lib\CORE" -L"C:\strawberry\c\lib" Json3.o   "C:\strawberry\perl\lib\CORE\libperl518.a" -lmoldname -lkernel32 -luser32 -lgdi32 -lwinspool -lcomdlg32 -ladvapi32 -lshell32 -lole32 -loleaut32 -lnetapi32 -luuid -lws2_32 -lmpr -lwinmm -lversion -lodbc32 -lodbccp32 -lcomctl32 -Wl,--enable-auto-image-base
"C:\strawberry\perl\bin\perl.exe" -MExtUtils::Command -e chmod -- 755 blib\arch\auto\JSON\Parse\Parse.dll
"C:\strawberry\perl\bin\perl.exe" -MExtUtils::Command -e cp -- script/validjson blib\script\validjson
pl2bat.bat blib\script\validjson

C:\strawberry\cpan\build\JSON-Parse-0.52-0>

I am running:

>perl -v

This is perl 5, version 18, subversion 4 (v5.18.4) built for MSWin32-x64-multi-thread

ExtUtils::ParseXS version 3.35

Thanks!

**Comment by benkasminbullock** [comment]
Thanks for the report. I have uploaded a new version, 0.53, to CPAN with
the bug fixed.

**Comment by gquipster** [comment]
Confirmed fix works - version 0.53 installed cleanly through cpan :-)

Thanks!

**Comment by benkasminbullock** [comment]
Thank you for the confirmation. I'll close this issue.
