### ISSUE TITLE
[Question] Where is the code for valid_json located?

### ISSUE THREAD

**Issue by sommmen** [benkasminbullock/JSON-Parse#42]
Hello!

I am a C# programmer and I am currently building a detector that checks the contents of a string (read from a file) for the content's type. It's for hobby so it does not need to be perfect. I have some logs in csv and xml and I am now using json more and more, so i would like to include something that checks whether the file contains (valid) json.

I was hoping the code for valid_json could point me in the right direction, but i can't wrap my head around perl. I assume the valid_json commands points to some function somewhere and i can read through the algorithm a bit and roll my own. Could you show me the right direction?

**Comment by benkasminbullock** [comment]
Most of the code is in C rather than in Perl and you don't seem to have made very much effort to look at the code, so I think this question is a bit invalid, sorry but I'm closing this issue.
