### ISSUE TITLE
Solaris cpan install

### ISSUE THREAD

**Issue by jMichaelA** [benkasminbullock/JSON-Parse#43]
I was trying to install this on a Solaris OS, but cpan install Json::Parse wasn't working. I downloaded the source code and there was this piece of code in the MakeFile.PL
`if ($^O =~ /solaris|sunos/i) {
    exit;
}`
(lines 5-7)

I took it out of the file and installed the package manually without any errors. I was wondering why this bit of code is included? We're running OmniOs if that helps any.

**Comment by benkasminbullock** [comment]
I believe this is because it was failing tests on Solaris. I'll remove that
code from Makefile.PL.

**Comment by benkasminbullock** [comment]
I guess this is OK now, please reopen if not.
