### ISSUE TITLE
JSON parser doubles the value string

### ISSUE THREAD

**Issue by SteveGlassman** [benkasminbullock/JSON-Parse#44]
I have tripped over a case in which simple JSON of the form: {"x":"\naaaaa..."} where there are 4079 "a" characters in a row will produce surprising output, once parsed.

I am using version 0.56 of JSON::Parse on version v5.18.2 of Perl on x86_64-linux-thread-multi.

If you put the above text in a file, as in the attached example (the size of the file should be 4090 characters) and then invoke JSON::Parse::json_file_to_perl() you will get an object that, when dumped, has 8158 "a" characters.  If you remove one of the "a" characters from the input file and repeat the parsing and dumping you will end up with 4078 "a" characters.  Adding an "a" instead of removing one gets you 4080 characters.

I'm attaching the test file that I've used.

[json.txt](https://github.com/benkasminbullock/JSON-Parse/files/4885271/json.txt)

**Comment by benkasminbullock** [comment]
Thank you for this bug report. I believe that I've identified the problem and resolved it. A new version of JSON::Parse is on CPAN:

https://metacpan.org/release/BKB/JSON-Parse-0.56_01

If you would like to confirm that the bug is resolved, please download the above and try it out on your problem. If this release goes through CPAN testers without issues, it will be released as version 0.57 within a day or two.

Thank you again.

**Comment by SteveGlassman** [comment]
Thanks so much for addressing this.

While I would love to test the fix, I'm afraid that I'm a bit too much of a newbie to know how to grab the data from a tar file and build it by hand.  I will, of course, follow any instructions that you can point me to, but unless they are as dirt-simple as the install from CPAN are, they may not fit into the time that I can devote right now.

Thanks again,
Steve

**Comment by benkasminbullock** [comment]
On Thu, 9 Jul 2020 at 04:41, Steve Glassman <notifications@github.com>
wrote:

> While I would love to test the fix, I'm afraid that I'm a bit too much of
> a newbie to know how to grab the data from a tar file and build it by hand.
> I will, of course, follow any instructions that you can point me to, but
> unless they are as dirt-simple as the install from CPAN are, they may not
> fit into the time that I can devote right now.
>
The tar file is on CPAN.

cpanm BKB/JSON-Parse-0.56_01.tar.gz

will install it for you.


>

**Comment by benkasminbullock** [comment]
Anyway, I think this is resolved, and you're not sure, so I'm closing it. Please feel free to reopen the issue if it reoccurs.

**Comment by SteveGlassman** [comment]
Ben,

I've verified that your new software addresses the issue.  Thanks for
resolving it so quickly.

Steve
