### ISSUE TITLE
Adding CI

### ISSUE THREAD

**Issue by szabgab** [benkasminbullock/JSON-Parse#45]
Would you be interested in a pull-request adding GitHub Actions configuration file?

**Comment by benkasminbullock** [comment]
Honestly I don't know what a github actions file is. I can add it if people
find it useful.

**Comment by szabgab** [comment]
GitHub Actions is the integrated CI system GitHub offers. It will run your tests (or whatever you tell it to run) every time you push code to GitHub. It can run it on multiple versions of Perl on the 3 major Operating Systems. Thereby it will shorten the feedback cycle for you.

**Comment by szabgab** [comment]
I cloned the repository and tried to run 

```
perl Makefile.PL 
```

I got the following error:

```
Could not open 'lib/JSON/Parse.pod': No such file or directory at .../perl5/ExtUtils/MM_Unix.pm line 2929.
```

How do you usually build your package from your repository?

**Comment by benkasminbullock** [comment]
On Tue, 10 Nov 2020 at 14:32, Gabor Szabo <notifications@github.com> wrote:

> I cloned the repository and tried to run
>
> perl Makefile.PL
>
> I got the following error:
>
> Could not open 'lib/JSON/Parse.pod': No such file or directory at .../perl5/ExtUtils/MM_Unix.pm line 2929.
>
> How do you usually build your package from your repository?
>

It is built using the script "build.pl" which uses modules I haven't
publicly released yet.


>

**Comment by szabgab** [comment]
Oh, then only you can build it. This process of setting up the CI system can help you clean up the code and the release system so anyone will be able to release a new version. If you are interested in that.

BTW I tried that too:

```
$ perl build.pl 
Undefined subroutine &main::perl_build called at build.pl line 5.
```

**Comment by benkasminbullock** [comment]
On Wed, 11 Nov 2020 at 15:21, Gabor Szabo <notifications@github.com> wrote:

> Oh, then only you can build it. This process of setting up the CI system
> can help you clean up the code and the release system so anyone will be
> able to release a new version. If you are interested in that.
>
I probably should sort the whole thing out at some point. The main reason
to use my own build system was to make better documentation. The private
name of my build module was called Perl::Build and then someone else
created a module on CPAN with the same name, causing some confusion.


> BTW I tried that too:
>
> $ perl build.pl
> Undefined subroutine &main::perl_build called at build.pl line 5.
>
>
I haven't released the module code anywhere at any point. I probably should
sort this out.

**Comment by benkasminbullock** [comment]
I'm gradually working on the CI issue, I now have the XS::Check pure Perl module and the C library unicode-c as well as an XS module called Image::PNG::QRCode under CI, I'm going to try to get this to be buildable from the github repository before version 0.58 is released. Thank you for the prodding.

**Comment by benkasminbullock** [comment]
I think it's possible to add CI now but no replies here so I'm closing this.
