### ISSUE TITLE
Do you want to know what this does?

### ISSUE THREAD

**Issue by majensen** [benkasminbullock/JSON-Parse#47]
Or do you prefer to be snark? If the latter, feel free to remove this reference. Thanks.

https://github.com/benkasminbullock/JSON-Parse/blob/9a652838019d01cc2b45573bcd58a83d4344ddc9/lib/JSON/Parse.pod.tmpl#L1415

**Comment by benkasminbullock** [comment]
I don't need to know what this module does.
