### ISSUE TITLE
Problems with tokenize_json in case of escaped double quotes

### ISSUE THREAD

**Issue by rainerhillebrand** [benkasminbullock/JSON-Parse#48]
I adapted the example script tokenize-synopsis.pl that is shipped with JSON::Parse 0.61 to demonstrate the issue:

```
#!/usr/bin/perl -w
use warnings 'all';
use strict;
use JSON::Tokenize ':all';
use JSON::Parse 'assert_valid_json';

my $input = '{"tuttie":["fruity\\"", true, 100]}';
eval {
	assert_valid_json ($input);
};
if ($@) {
	print "The JSON is invalid: $@\n";
}
else {
	print "The JSON is valid.\n";
}
my $token = tokenize_json ($input);
print_tokens ($token, 0);

sub print_tokens
{
    my ($token, $depth) = @_;
    while ($token) {
	my $start = tokenize_start ($token);
	my $end = tokenize_end ($token);
	my $type = tokenize_type ($token);
	print "   " x $depth;
	my $value = substr ($input, $start, $end - $start);
	print "'$value' has type '$type'.\n";
	my $child = tokenize_child ($token);
	if ($child) {
	    print_tokens ($child, $depth+1);
	}
	my $next = tokenize_next ($token);
	$token = $next;
    }
}
```

The result is:

```
C:\usr\local\bin>perl tokenize-synopsis.pl
The JSON is valid.
JSON::Parse: json-common.c:1308: Internal error at line 1: ',' is not a quote at end of string '"fruity\\""' at tokenize-synopsis.pl line 19.
```

As far as I know, the escaping of a double quote with a leading backslash is correct. assert_valid_json confirms this. However, tokenize_json seems to have a problem with it. Is the cause of this issue sitting in front of my keyboard or does the tokenize_json has an issue?

**Comment by benkasminbullock** [comment]
This seems to be an off-by-one error in some untested code. I have a fix but I want to check some things before releasing it. I will post an update here when a new test version is ready.

**Comment by benkasminbullock** [comment]
If you want to minimize JSON you don't really need JSON::Tokenize, just use JSON::Parse and JSON::Create without indentation and it will have all the whitespace removed automatically.

**Comment by benkasminbullock** [comment]
The underlying error in the tokenize part still exists so this bug can be kept open until that is fixed.

**Comment by benkasminbullock** [comment]
This should be OK with version 0.62.
